spring:
  datasource:
    url: jdbc:mysql://localhost:3306/be_sweet_circle
    username: root
    password: 0910886381018
  jpa :
    generate-ddl : true
    show-sql : true
    hibernate :
      ddl-auto : update
    properties :
      hibernate :
        globally_quoted_identifiers : true
        dialect : org.hibernate.dialect.MySQLDialect
        format_sql : true
